AWSTemplateFormatVersion: 2010-09-09
Description: The resources used to create the WebApp environment.
Parameters:
  EnvironmentName:
    Type: String
  ProjectName:
    Description: Primary project name
    Type: String
    Default: 'odamex'
  VPC:
    Type: String
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroup:
    Type: String
  DBClusterArn:
    Type: String
  DBAdminSecret:
    Type: String

Conditions:
  TestStage: !Equals [!Ref EnvironmentName, test]
  NotTestStage: !Not [Condition: TestStage]

Resources:
  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${ProjectName}-${EnvironmentName}-CodeBuildServiceRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub ${ProjectName}-${EnvironmentName}-CodeBuildServiceRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'cloudtrail:CreateTrail'
                  - 'cloudtrail:DeleteTrail'
                  - 'cognito-idp:*'
                  - 'ec2:*'
                  - 'lambda:*'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'rds:*'
                  - 'rds-data:*'
                  - 's3:*'
                  - 'secretsmanager:*'
                Effect: Allow
                Resource: '*'
              - Action:
                  - 'kms:Encrypt'
                  - 'kms:Decrypt'
                  - 'kms:ReEncrypt*'
                  - 'kms:GenerateDataKey*'
                  - 'kms:DescribeKey'
                Effect: Allow
                Resource:
                  - arn:aws:kms:us-east-1:370695041566:key/8bf6e3d2-955d-4764-9f8f-52e522753ca6
                  - arn:aws:kms:us-east-1:370695041566:key/a8a96f13-a527-4556-accc-e602e1cd1414
  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: latest
            build:
              commands:
                # --> LAMBDAS
                - npm install -g typescript

                # REST-API LAMBDA
                - cd $CODEBUILD_SRC_DIR/api/src && npm pkg delete scripts.prepare && npm install 
                - tsc 
                - npm prune --omit=dev 
                - zip -r dist.zip node_modules built package*.json
                - aws lambda update-function-code --function-name $ProjectName-$EnvironmentName-rest-api --zip-file fileb://dist.zip
              artifacts:
                base-directory: $CODEBUILD_SRC_DIR/app/dist
                files:
                  - '**/*'
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0'
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: EnvironmentName
            Value: !Ref EnvironmentName
          - Name: DB_Admin_Password
            Value: !Ref DBAdminSecret
      Name: !Sub ${ProjectName}-${EnvironmentName}-CodeBuildProject
      ServiceRole: !Ref CodeBuildServiceRole
      VpcConfig:
        VpcId: !Ref VPC
        Subnets: !Ref PrivateSubnets
        SecurityGroupIds:
          - !Ref SecurityGroup

Outputs:
  CodeBuildProject:
    Value: !Ref CodeBuildProject
