AWSTemplateFormatVersion: 2010-09-09
Description: Cognito Stack
Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name for cognito resources
    Default: dev
  ProjectName:
    Description: Primary project name
    Type: String
    Default: 'odamex'
  ProjectURL:
    Type: String
    Default: "odamex.net"
  EmailInvitationSubject:
    Type: String
    Default: >
      Family Planning Annual Report: Your User Account
  DBAdminSecret:
    Type: String
  DBClusterArn:
    Type: String
  ReplyToEmailAddress:
    Type: String
    Default: ""
  EmailDomainSourceArn:
    Type: String
    Default: ""

Conditions:
  IsLocal: !Equals
    - !Ref EnvironmentName
    - local
  IsDev: !Equals
    - !Ref EnvironmentName
    - dev
  IsQa: !Equals
    - !Ref EnvironmentName
    - qa
  IsStaging: !Equals
    - !Ref EnvironmentName
    - stg
  HasDefaultEmail: !Equals
    - !Ref EmailDomainSourceArn
    - ""

Resources:
  SNSRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${ProjectName}-${EnvironmentName}-SNSRole
      Tags:
        - Key: platform
          Value: odamex
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cognito-idp.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub ${ProjectName}-${EnvironmentName}-CognitoSNSPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "sns:publish"
                Resource: "*"

  # This section defines an execution role and Lambda functions called by Cognito to manage
  # actions and additional custom logic during the authentication process. 
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${ProjectName}-${EnvironmentName}-CognitoLambdasRole
      Tags:
        - Key: platform
          Value: odamex
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${ProjectName}-${EnvironmentName}-CognitoAuthorizedPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cognito-identity:*
                  - cognito-idp:*
                  - cognito-sync:*
                  - iam:ListRoles
                  - iam:ListOpenIdConnectProviders
                  - iam:GetRole
                  - iam:ListSAMLProviders
                  - iam:GetSAMLProvider
                  - kinesis:ListStreams
                  - lambda:GetPolicy
                  - lambda:ListFunctions
                  - sns:GetSMSSandboxAccountStatus
                  - sns:ListPlatformApplications
                  - ses:ListIdentities
                  - ses:GetIdentityVerificationAttributes
                  - mobiletargeting:GetApps
                  - acm:ListCertificates
                  - secretsmanager:GetSecretValue
                  - ssm:GetParameter
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action: iam:CreateServiceLinkedRole
                Resource: "*"
                Condition:
                  StringEquals:
                    "iam:AWSServiceName":
                      - "cognito-idp.amazonaws.com"
                      - "email.cognito-idp.amazonaws.com"
              - Effect: Allow
                Action:
                  - iam:DeleteServiceLinkedRole
                  - iam:GetServiceLinkedRoleDeletionStatus
                Resource:
                  - "arn:aws:iam::*:role/aws-service-role/cognito-idp.amazonaws.com/AWSServiceRoleForAmazonCognitoIdp*"
                  - "arn:aws:iam::*:role/aws-service-role/email.cognito-idp.amazonaws.com/AWSServiceRoleForAmazonCognitoIdpEmail*"
              - Effect: Allow
                Action: "rds-data:*"
                # RDS db cluster ARNs are not directly available - need to be constructed.
                # See https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_Tagging.ARN.html
                # So for now, leaving it out to save time. But ideally this would specify
                # this environment's db cluster only.
                Resource: "*"
              - Effect: Allow
                Action: "rds:DescribeDBClusters"
                # Same issue described above, we can't get the cluster ARN directly from the stack,
                # so granting access to describe attributes of all clusters.
                Resource: "*"

  CognitoUnAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${ProjectName}-${EnvironmentName}-CognitoUnAuthorizedRole
      Tags:
        - Key: platform
          Value: odamex
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": unauthenticated
      Policies:
        - PolicyName: !Sub ${ProjectName}-${EnvironmentName}-CognitoUnauthorizedPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                Resource: "*"

  CognitoAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${ProjectName}-${EnvironmentName}-CognitoAuthorizedRole
      Tags:
        - Key: platform
          Value: odamex
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: !Sub ${ProjectName}-${EnvironmentName}-CognitoAuthorizedPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                  - "cognito-identity:*"
                Resource: "*"

  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub "${ProjectName}-${EnvironmentName}-user-pool"
      UserPoolTags:
        platform: odamex
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: True
        InviteMessageTemplate:
          EmailMessage: !Sub >
            <html>
            <body>
            <font face="Calibri,sans-serif">
            <p>Dear Odamex user:</p>
            <p>An account was created for you.
            To connect to Odamex:</p>
            <ol style="margin-top:0;margin-bottom:0;">
            <li style="margin-bottom:10pt;">Navigate to <a href="https://${ProjectURL}">https://${ProjectURL}</a>.
            For the best experience, we recommend using Chrome, Edge, or Firefox.</li>
            <li style="margin-bottom:10pt;">Use the following credentials to log on:</li>
            </ol>
            <p style="margin:14pt 0 12pt 50pt;">
            Username: <b>{username}</b><br>
            Password: <b>{####}</b>
            </p>
            <ol start="3" style="margin-top:0;margin-bottom:0;">
            <li>When you log on to Odamex for the first time, you will be prompted to change your
            password and select your multifactor authentication method to verify your identity on 
            subsequent log-ins.</li>
            </ol>
            </body>
            </html>
          EmailSubject: !Ref EmailInvitationSubject
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          TemporaryPasswordValidityDays: 60
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      # UsernameAttributes:
      #   - email
      # UsernameConfiguration:
      #   CaseSensitive: false
      EnabledMfas:
        - SMS_MFA
        - SOFTWARE_TOKEN_MFA
      # LambdaConfig:
        # CustomMessage: !GetAtt LambdaCustomEmails.Arn
        # PreAuthentication: !GetAtt LambdaPrePostAuthTrigger.Arn
        # PostAuthentication: !GetAtt LambdaPrePostAuthTrigger.Arn
      MfaConfiguration: OPTIONAL
      SmsAuthenticationMessage: "Your FPAR authentication code is {####}"
      SmsVerificationMessage: "Your FPAR verification code is {####}"
      SmsConfiguration:
        ExternalId: !Sub "${ProjectName}-${EnvironmentName}-external"
        SnsCallerArn: !GetAtt SNSRole.Arn
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: metadata
          AttributeDataType: String
          Mutable: true
          StringAttributeConstraints:
            MaxLength: 2048
        - Name: last_login
          AttributeDataType: String
          Mutable: true
          Required: false
          StringAttributeConstraints:
            MinLength: 1
            MaxLength: 2048
      EmailConfiguration:
        EmailSendingAccount: !If [HasDefaultEmail, COGNITO_DEFAULT, DEVELOPER]
        From: !Sub "FPAR System <no-reply@${ProjectURL}>"
        ReplyToEmailAddress: !Ref ReplyToEmailAddress
        SourceArn:
          !If [HasDefaultEmail, !Ref AWS::NoValue, !Ref EmailDomainSourceArn]

  UserPoolAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Odamex admins group
      GroupName: Admins
      Precedence: 0
      # RoleArn: String
      UserPoolId: !Ref UserPool

  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Sub "${ProjectName}-${EnvironmentName}-client"
      GenerateSecret: false
      UserPoolId: !Ref UserPool
      AuthSessionValidity: 6

  IdentityPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      IdentityPoolName: !Sub "${EnvironmentName}Identity"
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  IdentityPoolRoleMapping:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthorizedRole.Arn
        unauthenticated: !GetAtt CognitoUnAuthorizedRole.Arn

  #LambdaPrePostAuthTriggerPermission:
  #  Type: AWS::Lambda::Permission
  #  Properties:
  #    Action: lambda:InvokeFunction
  #    FunctionName: !GetAtt LambdaPrePostAuthTrigger.Arn
  #    Principal: cognito-idp.amazonaws.com
  #    SourceArn: !GetAtt UserPool.Arn

Outputs:
  UserPoolId:
    Value: !Ref UserPool
  UserPoolArn:
    Value: !GetAtt UserPool.Arn
    Description: ARN for the user pool
  UserPoolClient:
    Description: The user pool app client id for web
    Value: !Ref UserPoolClient
  IdentityPoolId:
    Value: !Ref IdentityPool
