Parameters:
  EnvironmentName:
    Description: Environment name
    Type: String
    Default: 'dev'
    AllowedValues:
      - 'dev'
      - 'qa'
      - 'stg'
      - 'prod'
  RepositoryName:
    Description: Name of the github repo
    Type: String
  VeracodeParameterPrefix:
    Default: '/veracode'
    Description: Name of secret containing veracode information
    Type: String
  VeracodeSandboxName:
    Description: Sandbox name for Veracode dev scanning
    Type: String
Resources:
  CodeScanServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub MathRole-WeeklySASTScanServiceRole-${RepositoryName}-${EnvironmentName}
      PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/Math-Boundary-Policy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - codebuild.amazonaws.com
      Policies:
        - PolicyName: !Sub MathPolicy-WeeklySASTScanServiceRole-${RepositoryName}-${EnvironmentName}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  - codebuild:StopBuild
                  - codebuild:StartBuildBatch
                  - ecr:*
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - ssm:GetParameter
                  - ssm:DescribeParameters
                  - ssm:GetParameters
                Resource: '*'

  CodeScanProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${RepositoryName}-${EnvironmentName}-CodeScanProject-WEEKLY
      Artifacts:
        Type: NO_ARTIFACTS
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/mathematica-org/${RepositoryName}.git
        BuildSpec: !Sub |
          version: 0.2
          env:
            parameter-store:
              VERACODE_API_ID: "${VeracodeParameterPrefix}/id"
              VERACODE_API_KEY: "${VeracodeParameterPrefix}/key"
          phases:
            build:
              commands:
                - echo "***********************SCAN STAGE**********************"
                - TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
                - pwd
                - cd $CODEBUILD_SRC_DIR/lambdas/rest-portal-api
                - chmod +x ./sast-scan.sh
                - ls -l
                - zip -r ${RepositoryName}.zip src -x "*/.*"
                - ./sast-scan.sh $VERACODE_API_ID $VERACODE_API_KEY "PROD WEEKLY SCAN - ${RepositoryName} at $TIMESTAMP" ${RepositoryName}
                - cat /etc/os-release
      SourceVersion: main
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        # Follow https://docs.veracode.com/r/t_aws_config_codepipeline_static docs
        Image: 922539530544.dkr.ecr.us-east-1.amazonaws.com/veracode/java-api-wrapper:latest
        ImagePullCredentialsType: SERVICE_ROLE
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      ServiceRole: !Ref CodeScanServiceRole

Outputs:
  CodeScanProject:
    Value: !Ref CodeScanProject
