AWSTemplateFormatVersion: 2010-09-09
Description: Odamex backend application pipeline
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Information
        Parameters:
          - EnvironmentName
          - ProjectName
          - ServiceType
          - ProjectURL
          - HostedZoneId
          - EmailDomainSourceArn
          - AlertsEmailAddress
          - AWSApplicationArn
      - Label:
          default: Source Repository Information
        Parameters:
          - CodeConnectionArn
          - GitOrg
          - GitRepo
          - GitRepoBranch
      - Label:
          default: Network Information
        Parameters:
          - VPCID
          - VPCPrivateSubnets
          - VPCDefaultSecurityGroup
          - WAFArn
Parameters:
  EmailDomainSourceArn:
    Description: ARN for the SES verified identity
    Type: String
  EnvironmentName:
    Description: Environment name
    Type: String
    Default: 'dev'
    AllowedValues:
      - 'local'
      - 'dev'
      - 'qa'
      - 'stg'
      - 'prod'
  ProjectName:
    Description: Primary project name
    Type: String
    Default: 'odamex'
  ServiceType:
    Description: Type of service being deployed (e.g. "ui", "api", etc.)
    Type: String
    AllowedValues: 
      - "ui"
      - "api"    
  ProjectURL:
    Description: URL for the web application
    Type: String
    Default: ''
  HostedZoneId:
    Description: Route 53 hosted zone ID for the API custom domain
    Type: String
  AWSApplicationArn:
    Description: ARN of the associated, pre-defined AWS Application
    Type: String
    Default: ""
  AlertsEmailAddress:
    Description: Email address for receiving pipeline failures
    Type: String
    Default: ""    
  # Git info
  CodeConnectionArn:
    Description: CodeConnection ARN used to access the GitRepo repository
    Type: String
  GitOrg:
    Description: GitHub service account username owning the repo
    Type: String
    Default: "odamex"
  GitRepo:
    Description: GitHub app repo name
    Type: String
    Default: "reponame"
  GitRepoBranch:
    Description: GitHub repository branch name. It defaults to main if not specified.
    Type: String
    Default: "main"
  VPCID:
    Description: Existing VPC ID (provisioned by ITS)
    Type: AWS::EC2::VPC::Id
  VPCPrivateSubnets:
    Description: Private subnets associated with the existing VPC
    Type: List<AWS::EC2::Subnet::Id>
  VPCDefaultSecurityGroup:
    Description: Default security group associated with the existing VPC
    Type: AWS::EC2::SecurityGroup::Id
  WAFArn:
    Description: WAF V2 Web ACL Arn for API Gateway and CloudFormation (from ITS)
    Type: String

Conditions:
  IsDev: !Equals
    - !Ref EnvironmentName
    - dev
  IsProd: !Equals
    - !Ref EnvironmentName
    - prod
  IsNotProd: !Not
    - !Condition IsProd

Resources:
  # Role used to give CodePipeline to release a build.
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-CodePipelineServiceRole
      Tags:
        - Key: platform
          Value: odamex
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-CodePipelineServicePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # Allow codepipeline to put artifacts in the S3 bucket
              # as well as get artifacts back out of it.
              - Resource: '*' #  - !Sub arn:aws:s3:::${ArtifactBucket}/*
                Effect: Allow
                Action:
                  - s3:*
                  - ecr:*
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - codestar-connections:*
                  - iam:PassRole
                  - cloudformation:CreateChangeSet
                  - cloudformation:CreateStack
                  - cloudformation:CreateUploadBucket
                  - cloudformation:DeleteStack
                  - cloudformation:Describe*
                  - cloudformation:List*
                  - cloudformation:UpdateStack
                  - cloudformation:ValidateTemplate
                  - cloudformation:ExecuteChangeSet
                  - ssm:GetParameter
                  - ssm:DescribeParameters
                  - ssm:GetParameters

  # CloudFormation deployment role. This role is passed by CodeBuild to
  # CloudFormation to use when setting up the application resources
  CloudFormationDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-CloudFormationDeployRole
      Tags:
        - Key: platform
          Value: odamex
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-CloudFormationDeployPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'acm:*'
                  - 'apigateway:*'
                  - 'cloudformation:*'
                  - 'cloudfront:*'
                  - 'cloudtrail:*'
                  - 'cloudwatch:*'
                  - 'codebuild:*'
                  - 'codepipeline:*'
                  - 'cognito-identity:*'
                  - 'cognito-idp:*'
                  - 'dynamodb:*'
                  - 'ec2:*'
                  - 'ecr:*'
                  - 'ecs:*'
                  - 'events:*'
                  - 'iam:*'
                  - 'lambda:*'
                  - 'logs:*'
                  - 'rds:*'
                  - 'route53:*'
                  - 's3:*'
                  - 'secretsmanager:*'
                  - 'ses:*'
                  - 'sns:*'
                  - 'ssm:*'
                  - 'states:*'
                  - 'wafv2:*'
                Resource: '*'

  # While the build is in progress we need a place to store artifacts
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      Tags:
        - Key: platform
          Value: odamex
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowSSLRequestsOnly'
            Effect: 'Deny'
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt ArtifactBucket.Arn
              - !Join ['', [!GetAtt ArtifactBucket.Arn, '/*']]
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  # Infrastructure bucket to hold nested stacks and lambda code
  InfrastructureBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      BucketName: !Sub '${ProjectName}-${ServiceType}-${EnvironmentName}-infrastructure'
      Tags:
        - Key: platform
          Value: odamex
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - NoncurrentVersionTransition:
              NewerNoncurrentVersions: 5
              StorageClass: INTELLIGENT_TIERING
              TransitionInDays: 2557 # Number of days in 7 years
            Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      VersioningConfiguration:
        Status: Enabled
  InfrastructureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref InfrastructureBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowSSLRequestsOnly'
            Effect: 'Deny'
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt InfrastructureBucket.Arn
              - !Join ['', [!GetAtt InfrastructureBucket.Arn, '/*']]
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  # This pipeline defines the steps to build, deploy, and release the application
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-pipeline
      Tags:
        - Key: EnvironmentName
          Value: !Ref EnvironmentName
        - Key: platform
          Value: odamex
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      PipelineType: V2
      Stages:
        # First we have to pull the source code from the Github repository.
        - Name: Source
          Actions:
            - Name: Application
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !Ref CodeConnectionArn
                FullRepositoryId: !Sub ${GitOrg}/${GitRepo}
                BranchName: !Ref GitRepoBranch
                DetectChanges: false
              OutputArtifacts:
                - Name: AppArtifact
        - Name: Testing
          Actions:
              - Name: WebAppUnitTestsBuild
                Namespace: AppUnitTestingVars
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Version: '1'
                  Provider: CloudFormation
                Configuration:
                  ActionMode: CREATE_UPDATE
                  RoleArn: !GetAtt CloudFormationDeployRole.Arn
                  StackName: !Sub '${ProjectName}-${ServiceType}-${EnvironmentName}-app-build-tests-project'
                  TemplatePath: AppArtifact::infrastructure/stacks/app-tests-build.yml
                  Capabilities: CAPABILITY_NAMED_IAM
                  ParameterOverrides: !Sub |
                    { 
                      "EnvironmentName": "${EnvironmentName}",
                      "ProjectName": "${ProjectName}",
                    }
                InputArtifacts:
                  - Name: AppArtifact
                RunOrder: 1

            # app unit test
              - Name: WebAppUnitTests
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: '1'
                  Provider: CodeBuild
                Configuration:
                  ProjectName: '#{AppUnitTestingVars.CodeBuildProject}'
                  PrimarySource: AppArtifact
                InputArtifacts:
                  - Name: AppArtifact
                RunOrder: 2

        - Name: Resources
          Actions:
            # authentication
            - Name: AuthProvider
              Namespace: AuthVars
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationDeployRole.Arn
                StackName: !Sub '${ProjectName}-${ServiceType}-${EnvironmentName}-auth'
                TemplatePath: AppArtifact::infrastructure/stacks/auth.yml
                Capabilities: CAPABILITY_NAMED_IAM
                ParameterOverrides: !Sub |
                  {
                    "DBAdminSecret": "",
                    "DBClusterArn": "",
                    "EmailDomainSourceArn": "${EmailDomainSourceArn}",
                    "EnvironmentName": "${EnvironmentName}",
                    "ProjectName": "${ProjectName}",
                    "ProjectURL": "${ProjectURL}"
                  }
              InputArtifacts:
                - Name: AppArtifact
              RunOrder: 1

            #REST API
            - Name: APIRest
              Namespace: ApiRestVars
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationDeployRole.Arn
                StackName: !Sub '${ProjectName}-${ServiceType}-${EnvironmentName}-api-rest'
                TemplatePath: AppArtifact::infrastructure/stacks/api-rest.yml
                Capabilities: CAPABILITY_AUTO_EXPAND,CAPABILITY_NAMED_IAM
                ParameterOverrides: !Sub |
                    { 
                      "DatabaseSecurityGroup": "",
                      "DatabaseSubnetList": "",
                      "DBAdminSecret": "",
                      "EnvironmentName": "${EnvironmentName}",
                      "ProjectName": "${ProjectName}",
                      "HostedZoneId": "${HostedZoneId}",
                      "ProjectURL": "${ProjectURL}",
                      "UserPoolId": "#{AuthVars.UserPoolId}",
                      "UserPoolArn": "#{AuthVars.UserPoolArn}",  
                      "WAFArn": "${WAFArn}"
                    }
              InputArtifacts:
                - Name: AppArtifact
              RunOrder: 2

            #AppBuildVars - App build project
            - Name: AppBuildProject
              Namespace: AppBuildVars
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationDeployRole.Arn
                StackName: !Sub '${ProjectName}-${ServiceType}-${EnvironmentName}-app-build-project'
                TemplatePath: AppArtifact::infrastructure/stacks/app-build.yml
                Capabilities: CAPABILITY_NAMED_IAM
                ParameterOverrides: !Sub 
                  - |
                    { 
                      "EnvironmentName": "${EnvironmentName}",
                      "ProjectName": "${ProjectName}",
                      "VPC": "${VPCID}",
                      "PrivateSubnets": "${VPCSubnets}",
                      "SecurityGroup": "${VPCDefaultSecurityGroup}",
                      "DBAdminSecret": "",
                      "DBClusterArn": ""
                    }
                  - VPCSubnets: !Join [",", !Ref VPCPrivateSubnets]
              InputArtifacts:
                - Name: AppArtifact
              RunOrder: 5

            # builds app files
            # update S3
            # clears cloudfront dist
            - Name: Deploy
              Namespace: DeployVars
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: '#{AppBuildVars.CodeBuildProject}'
                PrimarySource: AppArtifact
              InputArtifacts:
                - Name: AppArtifact
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 6
      Triggers:
        - GitConfiguration:
            Push:
              - Branches:
                  Includes:
                    - !Ref GitRepoBranch
                FilePaths:
                  Includes:
                    - "./**"
                  Excludes:
                    - infrastructure/api-pipeline/**
            SourceActionName: Application
          ProviderType: CodeStarSourceConnection
