AWSTemplateFormatVersion: "2010-09-09"
Description: Produces a CloudFront-hosted website deployment pipeline
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Information
        Parameters:
          - EnvironmentName
          - ProjectName
          - ServiceType
          - DomainName
          - HostedZoneId
          - AlertsEmailAddress
          - AWSApplicationArn
      - Label:
          default: Source Repository Information
        Parameters:
          - CodeConnectionArn
          - GitOrg
          - GitRepo
          - GitRepoBranch
      - Label:
          default: Network Information
        Parameters:
          - SecurityHeadersPolicyId
          - VPCID
          - VPCDefaultSecurityGroup
          - WAFArn

Parameters:
  EnvironmentName:
    Description: Environment name
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "qa"
      - "stg"
      - "prod"
  ProjectName:
    Description: Primary project name
    Type: String
  ServiceType:
    Description: Type of service being deployed (e.g. "ui", "api", etc.)
    Type: String
    AllowedValues: 
      - "ui"
      - "api"
  DomainName:
    Type: String
  HostedZoneId:
    Description: Route 53 Hosted zone ID (for SSL certificate verification)
    Type: String
  AlertsEmailAddress:
    Description: Email address for receiving pipeline failures
    Type: String
    Default: ""
  AWSApplicationArn:
    Description: ARN of the associated, pre-defined AWS Application
    Type: String
    Default: ""
  UseVeracode:
    Description: Include Veracode scanning in the application pipeline
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "No"

  # Git info
  CodeConnectionArn:
    Description: CodeConnection ARN used to access the GitRepo repository
    Type: String
  GitOrg:
    Description: GitHub service account username owning the repo
    Type: String
    Default: "odamex"
  GitRepo:
    Description: GitHub app repo name
    Type: String
    Default: "reponame"
  GitRepoBranch:
    Description: GitHub repository branch name. It defaults to main if not specified.
    Type: String
    Default: "main"

  # VPC info
  SecurityHeadersPolicyId:
    Description: The ID of the AWS managed response header policy "SecurityHeadersPolicy"
    Type: String
    Default: "67f7725c-6f97-4210-82d7-5512b31e9d03"
  VPCID:
    Description: Existing VPC ID
    Type: AWS::EC2::VPC::Id
  VPCDefaultSecurityGroup:
    Description: Default security group associated with the existing VPC
    Type: AWS::EC2::SecurityGroup::Id
  WAFArn:
    Description: WAF v2 Web ACL arn
    Type: String

Conditions:
  IsProd: !Equals [!Ref EnvironmentName, prod]
  IsNotProd: !Not [Condition: IsProd]
  DoEmailAlerts: !Not [!Equals [AlertsEmailAddress, ""]]
  SetupVeracode: !Equals [!Ref UseVeracode, "Yes"]

Resources:
  # CloudFormation deployment role. This role is passed by CodeBuild to
  # CloudFormation to use when setting up the application resources
  CloudFormationDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-CloudFormationDeployRole
      Tags:
        - Key: platform
          Value: odamex
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-CloudFormationDeployPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "iam:*"
                  - "ec2:*"
                  - "ecs:*"
                  - "ecr:*"
                  - "rds:*"
                  - "ssm:*"
                  - "dynamodb:*"
                  - "lambda:*"
                  - "logs:*"
                  - "cloudwatch:*"
                  - "codepipeline:*"
                  - "route53:*"
                  - "s3:*"
                  - "cloudfront:*"
                  - "codebuild:*"
                  - "apigateway:*"
                  - "cognito-idp:*"
                  - "acm:*"
                  - "secretsmanager:*"
                  - "states:*"
                  - "events:*"
                  - "cognito-identity:*"
                  - "wafv2:*"
                Resource: "*"

  # Notification topic
  MySNSTopic:
    Type: AWS::SNS::Topic
    Condition: DoEmailAlerts
    Properties:
      Tags:
        - Key: platform
          Value: odamex
      Subscription:
        - Endpoint: !Ref AlertsEmailAddress
          Protocol: "email"
      TopicName: !Sub "${ProjectName}-${ServiceType}-${EnvironmentName}-UI-email-alerts"

  # Role used to give CodePipeline to release a build.
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-CodePipelineServiceRole
      Tags:
        - Key: platform
          Value: odamex
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-CodePipelineServicePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # Allow codepipeline to put artifacts in the S3 bucket
              # as well as get artifacts back out of it.
              - Resource: "*" #  - !Sub arn:aws:s3:::${ArtifactBucket}/*
                Effect: Allow
                Action:
                  - s3:*
                  - ecr:*
                  - ssm:*
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - codestar-connections:*
                  - iam:PassRole
                  - cloudformation:CreateChangeSet
                  - cloudformation:CreateStack
                  - cloudformation:CreateUploadBucket
                  - cloudformation:DeleteStack
                  - cloudformation:Describe*
                  - cloudformation:List*
                  - cloudformation:UpdateStack
                  - cloudformation:ValidateTemplate
                  - cloudformation:ExecuteChangeSet

  # While the build is in progress we need a place to store artifacts
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-artifacts
      Tags:
        - Key: platform
          Value: odamex
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 365
            Transitions:
              - TransitionInDays: 1
                StorageClass: GLACIER

  # The bucket requires this policy to only allow SSL requests
  # for Security Hub purposes
  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !GetAtt ArtifactBucket.Arn
              - !Join ["", [!GetAtt ArtifactBucket.Arn, "/*"]]
            Condition:
              Bool:
                aws:SecureTransport: "false"

  # This pipeline defines the steps to build, deploy, and release the application
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-pipeline
      Tags:
        - Key: EnvironmentName
          Value: !Ref EnvironmentName
        - Key: platform
          Value: odamex
        - Key: awsApplication
          Value: !Ref AWSApplicationArn
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      PipelineType: V2
      Stages:
        # First we have to pull the source code from the Github repository.
        - Name: Source
          Actions:
            - Name: Application
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !Ref CodeConnectionArn
                FullRepositoryId: !Sub ${GitOrg}/${GitRepo}
                BranchName: !Ref GitRepoBranch
                DetectChanges: false
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Testing
          Actions:
            - Name: WebAppUnitTestsBuild
              Namespace: AppUnitTestingVars
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationDeployRole.Arn
                StackName: !Sub "${ProjectName}-${ServiceType}-${EnvironmentName}-app-build-tests"
                TemplatePath: SourceArtifact::infrastructure/stacks/app-tests-build.yml
                Capabilities: CAPABILITY_NAMED_IAM
                ParameterOverrides: !Sub |
                  { 
                  	"EnvironmentName": "${EnvironmentName}",
                    "ProjectName": "${ProjectName}"
                  }
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

            # app unit test
            - Name: WebAppUnitTests
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Sub "#{AppUnitTestingVars.CodeBuildProject}"
                PrimarySource: SourceArtifact
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 2

        - Name: Resources
          Actions:
            # distribution - webapp S3 bucket, DNS records, CFront Distribution
            - Name: Distribution
              Namespace: DistributionVars
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationDeployRole.Arn
                StackName: !Sub "${ProjectName}-${ServiceType}-${EnvironmentName}-distribution"
                TemplatePath: SourceArtifact::infrastructure/stacks/distribution.yml
                Capabilities: CAPABILITY_NAMED_IAM
                ParameterOverrides: !Sub |
                  { 
                  	"EnvironmentName": "${EnvironmentName}",
                  	"DomainName": "${DomainName}",
                    "WAFArn": "${WAFArn}",
                    "ProjectName": "${ProjectName}",
                    "HostedZoneId": "${HostedZoneId}",
                    "SecurityHeadersPolicyId": "${SecurityHeadersPolicyId}"
                  }
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

            #AppBuildVars - App build front end
            - Name: AppBuild
              Namespace: AppBuildVars
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationDeployRole.Arn
                StackName: !Sub "${ProjectName}-${ServiceType}-${EnvironmentName}-app-build"
                TemplatePath: SourceArtifact::infrastructure/stacks/app-build.yml
                Capabilities: CAPABILITY_NAMED_IAM
                ParameterOverrides: !Sub |
                  { 
                  	"EnvironmentName": "${EnvironmentName}",
                  	"S3WebApp": "#{DistributionVars.S3WebApp}",
                  	"CloudFrontDistribution": "#{DistributionVars.CloudFrontDistribution}",
                  	"DomainName": "${DomainName}",
                    "ProjectName": "${ProjectName}",
                    "VPC": "${VPCID}",
                    "SecurityGroup": "${VPCDefaultSecurityGroup}"
                  }
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 2
        - Name: Deploy
          Actions:
            # builds app files
            # update S3
            # clears cloudfront dist
            - Name: Deploy
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Sub "#{AppBuildVars.CodeBuildProject}"
                PrimarySource: SourceArtifact
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
      Triggers:
        - GitConfiguration:
            Push:
              - Branches:
                  Includes:
                    - !Ref GitRepoBranch
                FilePaths:
                  Includes:
                    - "./**"
                  Excludes:
                    - infrastructure/api-pipeline/**
            SourceActionName: Application
          ProviderType: CodeStarSourceConnection