AWSTemplateFormatVersion: 2010-09-09
Description: The resources used to create the WebApp environment.
Parameters:
  EnvironmentName:
    Type: String
    Description: The name for the environment that this cloudformation will be part of.
  S3WebApp:
    Type: String
  ProjectName:
    Type: String
  DomainName:
    Type: String
  CloudFrontDistribution:
    Type: String
  VPC:
    Type: String
  SecurityGroup:
    Type: String
  CognitoUserPool:
    Type: String
    Default: ""
  CognitoClientId:
    Type: String
    Default: ""

Conditions:
  TestStage: !Equals [!Ref EnvironmentName, test]
  NotTestStage: !Not [Condition: TestStage]

Resources:
  CodeBuildServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub MathRole-${ProjectName}-CodeBuildServiceRole-UI-${EnvironmentName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub MathPolicy-${ProjectName}-CodeBuildServiceRole-UI-${EnvironmentName}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
              - Resource: "*"
                Effect: Allow
                Action:
                  - "ec2:*"
                  - "s3:*"
                  - "cloudfront:*"
                  - "cognito-idp:*"
                  - "secretsmanager:*"
                  - "kms:Encrypt"
                  - "kms:Decrypt"
                  - "kms:ReEncrypt*"
                  - "kms:GenerateDataKey*"
                  - "kms:DescribeKey"
  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: latest
            build:
              commands:
                # --> WEB APP
                # install and build the app
                - cd $CODEBUILD_SRC_DIR/
                - npm i
                - chmod +x config-generator.sh
                - ./config-generator.sh ${EnvironmentName} ${AWS::Region} ${DomainName} ${CognitoUserPool} ${CognitoClientId} > src/_config.ts
                - cat src/_config.ts
                - $BUILD_CMD
                # deploy app to s3
                - aws s3 sync ./dist/app "s3://$WEBBUCKET/"
                # --> DISTRIBUTION
                # clear cloudfront distribution
                - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*"
          artifacts:
            base-directory: $CODEBUILD_SRC_DIR/dist
            files:
              - '**/*'
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:5.0"
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: WEBBUCKET
            Value: !Ref S3WebApp
          - Name: CLOUDFRONT_DISTRIBUTION
            Value: !Ref CloudFrontDistribution
          - Name: BUILD_CMD
            Value: !Sub "npm run build:${EnvironmentName}"

      Name: !Sub ${ProjectName}-${EnvironmentName}-ui-CodeBuildProject
      ServiceRole: !Ref CodeBuildServiceRole

Outputs:
  CodeBuildProject:
    Value: !Ref CodeBuildProject
