AWSTemplateFormatVersion: 2010-09-09
Description: The resources used to create the WebApp environment.
Parameters:
  EnvironmentName:
    Type: String
    Description: The name for the environment that this cloudformation will be part of.
  ProjectName:
    Type: String
  ServiceType:
    Type: String

Conditions:
  TestStage: !Equals [!Ref EnvironmentName, test]
  NotTestStage: !Not [Condition: TestStage]

Resources:
  CodeTestBuildServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-CodeTestBuildServiceRole
      Tags:
        - Key: platform
          Value: odamex
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-CodeTestBuildServicePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
              - Resource: "*"
                Effect: Allow
                Action:
                  - "ec2:*"
                  - "s3:*"
                  - "cloudfront:*"
                  - "secretsmanager:*"
                  - "kms:Encrypt"
                  - "kms:Decrypt"
                  - "kms:ReEncrypt*"
                  - "kms:GenerateDataKey*"
                  - "kms:DescribeKey"
  CodeTestBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Tags:
        - Key: platform
          Value: odamex
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: latest
            build:
              commands:
                - cd $CODEBUILD_SRC_DIR/
                - npm i
                # - chmod +x config-generator.sh
                # - ./config-generator.sh ${ProjectName} ${ServiceType} ${EnvironmentName} ${AWS::Region} > src/_config.ts
                # - npm run prebuild
                # - npm run test-coverage
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:5.0"
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: EnvironmentName
            Value: !Ref EnvironmentName
      Name: !Sub ${ProjectName}-${ServiceType}-${EnvironmentName}-CodeTestBuildProject
      ServiceRole: !Ref CodeTestBuildServiceRole
    #   VpcConfig:
    #     VpcId: !Ref VPC
    #     Subnets: !Ref VPCSubnets
    #     SecurityGroupIds:
    #       - !Ref SecurityGroup

Outputs:
  CodeBuildProject:
    Value: !Ref CodeTestBuildProject
