AWSTemplateFormatVersion: "2010-09-09"
Description: The resources used to create the WebApp environment.
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  DomainName:
    Type: String
  ProjectName:
    Type: String
  ServiceType:
    Type: String
  WAFArn:
    Type: String
  HostedZoneId:
    Description: Custom hosted zone
    Type: String
  SecurityHeadersPolicyId:
    Type: String
    Description: The id of the AWS managed response header policy

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      Tags:
        - Key: platform
          Value: odamex
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub "www.${DomainName}"
          HostedZoneId: !Ref HostedZoneId
      SubjectAlternativeNames:
        - !Sub "www.${DomainName}"
      ValidationMethod: DNS

  S3WebApp:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${ServiceType}-${EnvironmentName}-ui"
      Tags:
        - Key: platform
          Value: odamex
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 365
            Transitions:
              - TransitionInDays: 1
                StorageClass: GLACIER

  S3WebAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3WebApp
      PolicyDocument:
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !GetAtt S3WebApp.Arn
              - !Join ["", [!GetAtt S3WebApp.Arn, "/*"]]
            Condition:
              Bool:
                aws:SecureTransport: "false"
          - Action:
              - s3:GetObject
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Resource: !Join ["", ["arn:aws:s3:::", !Ref S3WebApp, "/*"]]
            Condition:
              StringEquals:
                AWS:SourceArn:
                  !Join [
                    "",
                    [
                      !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/",
                      !Ref CloudFrontDistribution,
                    ],
                  ]

  # CloudFront
  CloudFrontDistributionLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${ServiceType}-${EnvironmentName}-cloudfront-distribution-logs"
      Tags:
        - Key: platform
          Value: odamex
      AccessControl: LogDeliveryWrite
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontDistributionLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudFrontDistributionLogBucket
      PolicyDocument:
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !GetAtt CloudFrontDistributionLogBucket.Arn
              - !Join ["", [!GetAtt CloudFrontDistributionLogBucket.Arn, "/*"]]
            Condition:
              Bool:
                aws:SecureTransport: "false"
          - Sid: AllowCloudFrontAccess
            Action: s3:GetObject
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Resource:
              !Join [
                "",
                ["arn:aws:s3:::", !Ref CloudFrontDistributionLogBucket, "/*"],
              ]
            Condition:
              StringEquals:
                AWS:SourceArn:
                  !Join [
                    "",
                    [
                      !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/",
                      !Ref CloudFrontDistribution,
                    ],
                  ]

  CloudFrontSecurityResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Comment: Extends Managed-SecurityHeadersPolicy to add set of security headers and Cache-Control:no-cache, no-store to every response
        CustomHeadersConfig:
          Items:
            - Header: Cache-Control
              Override: true
              Value: "no-cache, no-store"

            # Cloudfront will set the Server header value to "Cloudfront" after
            # removing the header, below, in RemoveHeadersConfig.
            # Override this by setting the header with an empty value to
            # satisfy the WAS scan finding of exposing server details.
            - Header: Server
              Override: true
              Value: ""
        Name: !Sub ${ProjectName}_${EnvironmentName}_Security_Response_Headers_Policy
        SecurityHeadersConfig:
          ContentTypeOptions:
            Override: true
          ContentSecurityPolicy:
            ContentSecurityPolicy: !Sub "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: https:; connect-src 'self' api.${DomainName} cognito-idp.${AWS::Region}.amazonaws.com https:;"
            Override: true
          FrameOptions:
            FrameOption: SAMEORIGIN
            Override: false
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: false
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Override: false
          XSSProtection:
            ModeBlock: true
            Override: false
            Protection: true
        RemoveHeadersConfig:
          Items:
            - Header: Server

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: !Sub "OAC for ${ProjectName}-${ServiceType}-${EnvironmentName}"
        Name: !Sub "${ProjectName}-${ServiceType}-${EnvironmentName}-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontCachingDisabledCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: "Policy with caching disabled"
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        Name: !Sub ${ProjectName}_${EnvironmentName}Caching_Disabled_Cache_Policy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: false
          EnableAcceptEncodingBrotli: false
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - CloudFrontDistributionLogBucket
    Properties:
      Tags:
        - Key: platform
          Value: odamex
      DistributionConfig:
        Aliases: !Split [",", !Sub "${DomainName}"]
        DefaultCacheBehavior:
          CachePolicyId: !Ref CloudFrontCachingDisabledCachePolicy
          Compress: true
          TargetOriginId: !Ref S3WebApp
          ViewerProtocolPolicy: redirect-to-https
          ResponseHeadersPolicyId: !Ref CloudFrontSecurityResponseHeadersPolicy
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        Enabled: true
        HttpVersion: http2
        Logging:
          Bucket: !GetAtt CloudFrontDistributionLogBucket.DomainName
        Origins:
          - DomainName: !GetAtt S3WebApp.DomainName
            Id: !Ref S3WebApp
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: "TLSv1.2_2021"
          SslSupportMethod: "sni-only"
        WebACLId: !Ref WAFArn

  # DNS records
  DnsRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${DomainName}"
      Type: "A"
  DnsRecordWWW:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "www.${DomainName}"
      Type: "A"
  DnsRecordIPv6:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${DomainName}"
      Type: "AAAA"
  DnsRecordIPv6WWW:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "www.${DomainName}"
      Type: "AAAA"

Outputs:
  S3WebApp:
    Value: !Ref S3WebApp
  CloudFrontDistribution:
    Value: !Ref CloudFrontDistribution
