Parameters:
  EnvironmentName:
    Description: Environment name
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "qa"
      - "stg"
      - "prod"
  ProjectName:
    Type: String
    Description: Project short name
  VeracodeSandboxName:
    Description: Sandbox name for Veracode dev scanning
    Type: String
Resources:
  CodeScanServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub MathRole-SASTScanServiceRole-${ProjectName}-${EnvironmentName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - codebuild.amazonaws.com
      Policies:
        - PolicyName: !Sub MathPolicy-SASTScanServiceRole-${ProjectName}-${EnvironmentName}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: "*"
              - Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  - codebuild:StopBuild
                  - codebuild:StartBuildBatch
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:*
                Resource: "*"

  CodeScanProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ProjectName}-${EnvironmentName}-CodeScanProject
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            build:
              commands:
                - echo "***********************SCAN STAGE**********************"
                - pwd
                - cd $CODEBUILD_SRC_DIR
                - chmod +x ./sast-scan.sh
                - ls -l
                - zip -r ${ProjectName}.zip src -x "*/.*"
                - ./sast-scan.sh {{resolve:ssm:VeracodeId}} {{resolve:ssm:VeracodeKey}} "Scan from AWS deployment - $CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_START_TIME" ${ProjectName}
                - cat /etc/os-release
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        # Follow https://docs.veracode.com/r/t_aws_config_codepipeline_static docs
        Image: 922539530544.dkr.ecr.us-east-1.amazonaws.com/veracode/java-api-wrapper:latest
        ImagePullCredentialsType: SERVICE_ROLE
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      ServiceRole: !Ref CodeScanServiceRole

Outputs:
  CodeScanProject:
    Value: !Ref CodeScanProject
