AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  dbCluster:
    Type: String
    Description: ARN of the database cluster
  endpoint:
    Type: String
    Description: The Secrets Manager endpoint to use.
  env:
    AllowedValues:
      - local
      - dev
      - qa
      - stg
      - prod
    Description: Environment name
    Type: String
  excludeCharacters:
    Type: String
    Description: A string of the characters that you don't want in the password.
    Default: ":/@\"'\\"
  functionName:
    Type: String
    Description: The name of the Lambda function.
  invokingServicePrincipal:
    Type: String
    Description: The service principal for the invoking service.
    Default: 'secretsmanager.amazonaws.com'
  kmsKeyArn:
    Type: String
    Description: The ARN of the KMS key that Secrets Manager uses to encrypt the secret.
    Default: ''
  runtime:
    Type: String
    Description: The python runtime associated with the Lambda function
    Default: 'python3.13'
  secretRotationCodeVersionId:
    Type: String
    Description: S3 version ID of deployment package for secret rotation lambda code
  vpcSecurityGroupIds:
    Type: CommaDelimitedList
    Description: A comma-separated list of security group IDs applied to the database.
    Default: ''
  vpcSubnetIds:
    Type: CommaDelimitedList
    Description: A comma-separated list of VPC subnet IDs applied to the database network.
    Default: ''

Conditions:
  AddVpcConfig: !And
    - !Not [!Equals ['', !Join ['', !Ref vpcSubnetIds]]]
    - !Not [!Equals ['', !Join ['', !Ref vpcSecurityGroupIds]]]
  KmsKeyArnExists: !Not [!Equals ['', !Ref kmsKeyArn]]

Resources:
  SecretsManagerRDSPostgreSQLRotationSingleUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref functionName
      Description: Rotates a Secrets Manager secret for Amazon RDS PostgreSQL credentials using the single user rotation strategy.
      Handler: lambda_function.lambda_handler
      Runtime: !Ref 'runtime'
      CodeUri:
        Bucket: !Sub ${env}-odamex-infrastructure
        Key: SecretsManagerRDSPostgreSQLRotationSingleUser.zip
        Version: !Ref secretRotationCodeVersionId
      AutoPublishAlias: latest
      Timeout: 30
      Policies:
        - AmazonRDSFullAccess
        - AmazonRDSDataFullAccess
        - VPCAccessPolicy: {}
        - AWSSecretsManagerRotationPolicy:
            FunctionName:
              Ref: functionName
        - !If
          - KmsKeyArnExists
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:DescribeKey
                  - kms:GenerateDataKey
                Resource: !Ref kmsKeyArn
          - !Ref 'AWS::NoValue'
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 'codepipeline:ListPipelines'
                - 'codepipeline:StartPipelineExecution'
              Resource: '*'
      Environment:
        Variables:
          SECRETS_MANAGER_ENDPOINT:
            Ref: endpoint
          EXCLUDE_CHARACTERS:
            Ref: excludeCharacters
          ENV:
            Ref: env
      VpcConfig: !If
        - AddVpcConfig
        - SubnetIds: !Ref vpcSubnetIds
          SecurityGroupIds: !Ref vpcSecurityGroupIds
        - !Ref 'AWS::NoValue'
      Tags:
        SecretsManagerLambda: Rotation

  LambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt SecretsManagerRDSPostgreSQLRotationSingleUser.Arn
      Principal: !Ref invokingServicePrincipal
      SourceAccount: !Ref 'AWS::AccountId'

Outputs:
  RotationLambdaARN:
    Description: The ARN of the rotation lambda
    Value: !GetAtt SecretsManagerRDSPostgreSQLRotationSingleUser.Arn
