all: true
branches: 10
check-coverage: true
exclude:
    - built
    - src/**/*.spec.ts
    - src/types/*
extension:
    - .ts
functions: 10
include:
    - src/**/*.ts
lines: 10
reporter:
    - html
    - text
statements: 10
watermarks:
    branches:
        - 0
        - 80
    functions:
        - 0
        - 80
    lines:
        - 0
        - 80
    statements:
        - 0
        - 80
